trigger:
- master

variables:
  #base version: "0.5"
  BuildConfiguration: "Release"
  project file: "Alex75.BinanceApiClient/Alex75.BinanceApiClient.fsproj"
  package version: $(Version.MajorMinor).$(Build.BuildNumber)

jobs:

- job: GetVersion
  steps:
    - bash: echo "Get the project Main.Minor version"
    - task: tmarkovski.projectversionasvariable.versionintovariable.projectversionasvariable@1
      displayName: 'Get Project Version as variables from $(project file)'
      inputs:
        path: '$(project file)'

- job: Build
  dependsOn: GetVersion
  steps:
    - bash: echo "Build the solution $(package version)"

