trigger:
- master

variables:
  base version: "0.5"
  project file: "Alex75.BinanceApiClient/Alex75.BinanceApiClient.fsproj"
  package version: $(Version.MajorMinor).$(Build.BuildNumber)

jobs:

#- job: GetVersion
#  steps:
#    - bash: echo "Get the project Main.Minor version"
#    - task: tmarkovski.projectversionasvariable.versionintovariable.projectversionasvariable@1
#      displayName: 'Get Project Version as variables from $(project file)'
#      inputs:
#        path: '$(project file)'

#- job: Check Version
#  dependsOn: GetVersion
#  steps:
#    - bash: echo "Build the solution $(package version)"

#- job: Build
#  steps:
#    - task: DotNetCoreCLI@2
#      displayName: Build
#      inputs: 
#        command: build
#        projects: "$(project file)"
#        arguments: --configuration Release 

- job: Test
  #dependsOn: Build
  steps: 
    - task: DotNetCoreCLI@2
      displayName: Tests
      inputs:
        command: test
        #projects: "**/*Tests.*proj"
        projects: "IntegrationTests/IntegrationTests.fsproj"
        arguments: >
          --configuration Release 
          --filter "TestCategory!=AFFECT_BALANCE & TestCategory!=REQUIRE_API_KEY""