# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  - name: version
    value: "1.1"
  - name: project file
    value: "Alex75.BinanceApiClient/Alex75.BinanceApiClient.fsproj"    
  - name: build number
    value: $[counter(variables.version, 1)] # counter that is reset to 1 every time "version" change
  - name: package version
    value: "$(version).$(build number)"
  - group: general # Library varialbles group name 
  - name: nuget api key
    value: $[variables.NUGET_API_KEY]


steps:
- script: dotnet build -c Release
  displayName: "Build"

- script: dotnet build -c Release
  displayName: "Test"

- script: dotnet test --configuration Release --no-build --filter "TestCategory!=AFFECTS_BALANCE & TestCategory!=REQUIRES_API_KEY & TestCategory!=SKIP_ON_DEPLOY"
  displayName: dotnet test

- script: dotnet pack $(project file) -c Release --no-build -p:PackageVersion="$(package version)"
  displayName: "Pack NuGet"

#- script: |
#    echo Created package version "$(package version)"
#    # removed "--no-build" due to the error "The 'NoBuild' property was set to true but the 'Build' target was invoked"
#    dotnet pack "$(project file)" -c Release  -p:PackageVersion="$(package version)"
#  displayName: 'Pack NuGet'