# it works also without "resources" but when cahange the repository name in GitHub it will be lost
resources:
  #containers: 
  repositories:
  - repository: GitHub
    type: github
    name: alex75it/BinanceApiClient
    endpoint: alex75it 
    # GitHub service connection name (defined in Project Settings > GitHub connections)

trigger:
- master

pool:
  # pre/post build commands require Windows machine
  vmImage: 'windows-latest'

variables:
  version: "0.9"
  project file: "Alex75.BinanceApiClient/Alex75.BinanceApiClient.fsproj"
  # counter that is reset to 1 every time "version" change
  build number: $[counter(variables.version, 1)]
  package version: "$(version).$(build number)"

jobs:

- job: Build
  steps:
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs: 
        command: build
        projects: "$(project file)"
        arguments: --configuration Release 

    - task: DotNetCoreCLI@2
      displayName: Tests
      inputs:
        command: test
        projects: "**/*Tests.*proj"
        arguments: >
          --configuration Release 
          --filter "TestCategory!=AFFECTS_BALANCE & TestCategory!=REQUIRES_API_KEY & TestCategory!=SKIP_ON_DEPLOY"

- job: NuGet
  dependsOn: Build
  steps: 
    - bash: echo "Publish package version $(package version)"
    - task: DotNetCoreCLI@2
      displayName: "Create package"
      inputs:
        command: pack
        packagesToPack: "$(project file)"
        versioningScheme: byEnvVar
        versionEnvVar: "package version"    

    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'Alex75 Nuget'