# Azure pipeline
# it works also without "resources" but when change the repository name in GitHub it will be lost

resources:
  #containers: 
  repositories:
  - repository: GitHub
    type: github
    name: alex-piccione/BinanceApiClient
    endpoint: alex75it 
    # GitHub service connection name (defined in Project Settings > GitHub connections)

trigger:
  branches:
    include:
    - "feature/*"
    exclude:
    - master

pool:
  # pre/post build commands require Windows machine
  vmImage: 'windows-latest'

variables:
  version: "1.1"
  project file: "Alex75.BinanceApiClient/Alex75.BinanceApiClient.fsproj"
  # counter that is reset to 1 every time "version" change
  build number: $[counter(variables.version, 1)]
  package version: "$(version).$(build number)-alpha"

jobs:

- job: Build
  steps:
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs: 
        command: build
        projects: "$(project file)"
        arguments: --configuration Release 

    - task: DotNetCoreCLI@2
      displayName: Tests
      inputs:
        command: test
        projects: "**/*Tests.*proj"
        arguments: >
          --configuration Release 
          --filter "TestCategory!=AFFECTS_BALANCE & TestCategory!=REQUIRES_API_KEY & TestCategory!=SKIP_ON_DEPLOY"
